web.config

Remove application directory

---

build.gradle
src/functionalTest/resources/json/formData.json
src/functionalTest/resources/json/formDataMultiples.json
src/functionalTest/resources/json/inviteDataInvalid.json
src/functionalTest/resources/json/inviteDataValid.json
src/functionalTest/uk/gov/hmcts/probate/functional/BusinessServiceBusinessValidationControllerTests.java
src/functionalTest/uk/gov/hmcts/probate/functional/BusinessServiceInvitationControllerTests.java
src/functionalTest/uk/gov/hmcts/probate/functional/BusinessServicePinControllerTests.java
src/functionalTest/uk/gov/hmcts/probate/functional/IntegrationTestBase.java
src/functionalTest/uk/gov/hmcts/probate/functional/TestContextConfiguration.java
src/functionalTest/uk/gov/hmcts/probate/functional/TestUtils.java
src/test/resources/application.properties

- Added test cases for the 3 controllers in the service
- Tested hitting the API end point with different data and values
- Ensure that the correct response codes and messages were returned from those calls
```
[ ] Yes
[ ] No
```

PRO-2829: Functional Tests for Business Service

---

.travis.yml
Jenkinsfile_parameterized

Pro 2844 add archive

---

src/functionalTest/java/uk/gov/hmcts/probate/functional/IntegrationTestBase.java

PRO-2829: Re-name config setup method to avoid confusion

---

build.gradle

PRO-2886: update security check plugin

---

.gitignore
build.gradle
src/main/java/uk/gov/hmcts/probate/BusinessApplication.java
src/main/resources/application.properties
src/test/java/uk/gov/hmcts/probate/services/business/services/GitCommitInfoEndpointTest.java
src/test/resources/uk/gov/hmcts/probate/services/business/git-test.properties

https://tools.hmcts.net/jira/browse/PRO-2831
Update to remove web application context from the git hash test which was upsetting the rest of the application tests where the context was being used for bean creation.
```
[ ] Yes
[x] No
```

Pro 2831 git hash health check end point business service

---

Jenkinsfile_CNP
build.gradle
src/test/java/uk/gov/hmcts/probate/insights/AppInsightsTest.java
src/test/java/uk/gov/hmcts/probate/services/business/services/GitCommitInfoEndpointTest.java

https://tools.hmcts.net/jira/browse/PRO-3059
Implemented Mutation testing, fixed tests that were failing/missing causing issues with mutation testing
```
[ ] Yes
[X] No
```

PRO-3059 Added Mutation Testing

---

src/main/java/uk/gov/hmcts/probate/services/idgeneration/strategy/ProbateStrategy.java
src/test/java/uk/gov/hmcts/probate/services/invitation/unit/IdGeneratorServiceTest.java

[PREVIEW] PRO-3337: strip special characters from invite id

---

infrastructure/preview.tfvars
src/functionalTest/java/uk/gov/hmcts/probate/functional/BusinessServiceInvitationControllerTests.java
src/functionalTest/resources/json/emptyInviteData.json
src/main/java/uk/gov/hmcts/probate/services/invitation/InvitationService.java
src/main/java/uk/gov/hmcts/probate/services/invitation/controllers/InvitationController.java

Pro 2676 notify new email send

---

Jenkinsfile_CNP

remove pi test

---

build.gradle
src/test/java/uk/gov/hmcts/probate/services/persistence/unit/PersistenceClientTest.java

Additional unit test coverage
```
[ ] Yes
[ x] No
```

PRO-3820: additional unit tests

---

src/test/java/uk/gov/hmcts/probate/services/document/unit/DocumentValidationTest.java
src/test/java/uk/gov/hmcts/probate/services/pin/integration/PinControllerTest.java

Increase test coverage
```
[ ] Yes
[X] No
```

PRO-3820: Increased test coverage

---

Dockerfile
build.gradle
charts/probate-business-service/requirements.yaml

Bump chart ver to 0.0.10

---

infrastructure/sprod.tfvars

https://tools.hmcts.net/jira/browse/PRO-4716
```
[ ] Yes
[ ] No
```

PRO-4716: amend business_service_notify_invitedata_invitelink

---

Dockerfile

PRO-4733
```
[ ] Yes
[ x] No
```

PRO-4733 update java

---

Jenkinsfile_nightly
security.sh

set up probate business service security scan

---

infrastructure/main.tf
infrastructure/state.tf

Remove terraform remote state

---

config/owasp/suppressions.xml

Add suppressions

---

Jenkinsfile_CNP

Add SIDAM curl & break pipeline

---

Jenkinsfile_CNP

break pipeline

---

Jenkinsfile_CNP

unbreak prod pipeline

---

build.gradle
config/owasp/suppressions.xml

Pro 5640 owasp update

---

Jenkinsfile_CNP
build.gradle
config/owasp/suppressions.xml

merging to demo

---

config/owasp/suppressions.xml

add suppressions update

---

charts/probate-business-service/requirements.yaml

upgd java chart and pull from hmctspublic

---

src/main/resources/templates/pdf/bulkScanCoverSheet.html

https://tools.hmcts.net/jira/browse/PRO-5888
Minor update to amend coversheet to meet intentions of Exela regarding position of applicant name.
```
[ ] Yes
[x] No
```

PRO-5888 Tweak to coversheet to update position of applicant name

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PRO-5888
Add suppression for a couple of databind issues with release 2.9.8.
```
[ ] Yes
[x] No
```

PRO-5888: Fix suppression issues with merged update.

---

Jenkinsfile_CNP
README.md
charts/probate-business-service/values.aat.template.yaml
charts/probate-business-service/values.yaml
src/main/resources/application.yml

Aks enable staging deploy

---

Dockerfile
README.md

Testing pr

---

Dockerfile
build.gradle
charts/probate-business-service/values.aat.template.yaml
charts/probate-business-service/values.preview.template.yaml
charts/probate-business-service/values.sandbox.template.yaml
charts/probate-business-service/values.yaml
src/main/resources/bootstrap.yaml

Added logging version

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/probate/services/invitation/InvitationService.java
src/main/java/uk/gov/hmcts/probate/services/invitation/controllers/InvitationController.java
src/main/java/uk/gov/hmcts/probate/services/invitation/model/Invitation.java
src/test/java/uk/gov/hmcts/probate/services/invitation/unit/InvitationServiceTest.java
src/test/resources/invitation/expectedDecoding.json
src/test/resources/invitation/success.json

https://tools.hmcts.net/jira/browse/PRO-5526
Allow executors to be notified if there is an accent in any names. 
```
[ ] Yes
[x] No
```

Pro 5526 fix accents bug

---

Jenkinsfile_CNP

Disable Legacy Deployment

---

charts/probate-business-service/Chart.yaml

Update infra. version

---

Jenkinsfile_CNP

PRO-1234: Unbreak Pipeline

---

build.gradle

PRO-1234: upgrade commons

---

Jenkinsfile_CNP

Unbreak build to prod for 20 02 2020

UnbreakBuildForProd2002

---

build.gradle

PRO-6841: Reference new version of commons library

---

src/test/java/uk/gov/hmcts/probate/services/businessdocuments/unit/BusinessDocumentControllerTest.java
src/test/resources/businessdocuments/validLegalDeclarationOneDec.json

https://tools.hmcts.net/jira/browse/PRO-6841
Added test for negative scenario.
```
[ ] Yes
[X ] No
```

PRO-6841: added test for code coverage WLA-244

---

Jenkinsfile_CNP

Go live on AKS Prod

---

.travis.yml
Dockerfile
Jenkinsfile_CNP
build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PRO-7898
Java 11 changes
```
[ ] Yes
[X] No
```

PRO-7898 Java 11 code changes

---

Jenkinsfile_CNP
Jenkinsfile_parameterized
build.gradle
config/owasp/suppressions.xml
src/functionalTest/java/uk/gov/hmcts/probate/functional/BulkScanCoverSheetPDFTest.java
src/functionalTest/java/uk/gov/hmcts/probate/functional/BusinessDocumentControllerTest.java
src/functionalTest/java/uk/gov/hmcts/probate/functional/BusinessServiceBusinessValidationControllerTests.java
src/functionalTest/java/uk/gov/hmcts/probate/functional/BusinessServiceDocumentControllerTests.java
src/functionalTest/java/uk/gov/hmcts/probate/functional/BusinessServiceInvitationControllerTests.java
src/functionalTest/java/uk/gov/hmcts/probate/functional/BusinessServicePinControllerTests.java
src/functionalTest/java/uk/gov/hmcts/probate/functional/BusinessServiceServiceAuthTokenGenerator.java
src/functionalTest/java/uk/gov/hmcts/probate/functional/CheckSummaryAnswerPDFTest.java
src/functionalTest/java/uk/gov/hmcts/probate/functional/IntegrationTestBase.java
src/functionalTest/java/uk/gov/hmcts/probate/functional/LegalDeclarationPDFTest.java
src/functionalTest/java/uk/gov/hmcts/probate/functional/PDFIntegrationBase.java
src/functionalTest/java/uk/gov/hmcts/probate/functional/TestContextConfiguration.java
src/functionalTest/resources/application.properties
src/functionalTest/resources/json/validLegalDeclaration.json
src/functionalTest/resources/json/validLegalDeclarationForMultipleExecutors.json

https://tools.hmcts.net/jira/browse/PRO-7827
Serenity implementation
```
[ ] Yes
[ X ] No
```

Pro 7827 serenity implementation

---

README.md
docker-compose.yml

Update dev env to use jar
https://tools.hmcts.net/jira/browse/DTSPB-573

update dev env

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/DTSPB-631
Owasp version upgrade
```
[ ] Yes
[ X ] No
```

DTSPB-631 Owasp version upgrade

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/DTSPB-111
Update commons to 1.1.0.2
```
[ ] Yes
[x] No
```

Update commons to 1.1.0.2

---

Jenkinsfile_CNP
config/owasp/suppressions.xml

TA-166: Add suppression for junit

---

config/owasp/suppressions.xml
src/functionalTest/java/uk/gov/hmcts/probate/functional/BusinessServiceInvitationControllerTests.java
src/functionalTest/java/uk/gov/hmcts/probate/functional/BusinessServicePinControllerTests.java
src/functionalTest/resources/json/inviteDataInvalid.json
src/test/java/uk/gov/hmcts/probate/services/pin/integration/PinControllerTest.java

https://tools.hmcts.net/jira/browse/DTSPB-1039
Added new test for pin and invite controller
```
[ ] Yes
[ x] No
```

Added new test for pin and invite controller

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/DTSPB-529
Point to commons 1.1.1
```
[ ] Yes
[x] No
```

Point to commons 1.1.1

---

build.gradle
charts/probate-business-service/Chart.yaml
charts/probate-business-service/requirements.yaml
config/owasp/suppressions.xml
src/main/resources/application.properties
src/main/resources/application.yml

https://tools.hmcts.net/jira/browse/DTSPB-891
Java chart version upgrade
```
[ ] Yes
[X ] No
```

DTSPB-891 Java chart version update

---

Jenkinsfile_CNP
build.gradle
src/contractTest/java/uk/gov/hmcts/probate/services/consumer/DocumentServiceConsumerTest.java

Fix pact jupiter tests

---

build.gradle
suppressions.xml

https://tools.hmcts.net/jira/browse/DTSPB-1647
https://tools.hmcts.net/jira/browse/DTSPB-1543
resolve Bouncycastle And Guava supressed dependencies
```
[ ] Yes
[ X] No
```

DTSPB-1647 resolve Bouncycastle And Guava supressed dependencies

---

build.gradle
suppressions.xml

https://tools.hmcts.net/jira/browse/DTSPB-1650
https://tools.hmcts.net/jira/browse/DTSPB-1652
changes to resolve supressions
```
[ ] Yes
[X ] No
```

DTSPB-1650-52 changes to fix two suppressions

---

build.gradle
suppressions.xml

https://tools.hmcts.net/jira/browse/DTSPB-1649
CVE resolution
[ ] Yes
[X ] No

DTSPB-1649 tomcat related suppressions resolution

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSPB-1686
CVE resolution
[ ] Yes
[ X ] No

DTSPB-1686 resolve CVE-2021-22112

---

build.gradle
suppressions.xml

https://tools.hmcts.net/jira/browse/DTSPB-1686
CVE resolution
[ ] Yes
[ X ] No

DTSPB-1686 Update the previous fix for CVE-2021-22112

---

build.gradle
suppressions.xml

https://tools.hmcts.net/jira/browse/DTSPB-1651
Resolve CVE-2020-15250
```
[ ] Yes
[X ] No
```

DTSPB-1651 Resolve CVE-2020-15250

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSPB-1651
Added pitest related dependency back and added junit upper version as a transitive dependencies  
```
[ ] Yes
[ X ] No
```

DTSPB-1651 Better fix for CVE-2020-15250 with junit

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSPB-1775
updated commons version
```
[ ] Yes
[X] No
```

DTSPB-1775 updated commons version

---

charts/probate-business-service/Chart.yaml

https://tools.hmcts.net/jira/browse/DTSPB-1843
Updated the version of the charts yml and the java api version
```
[ ] Yes
[X] No
```

DTSPB-1843 Updated the Java chart version 

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSPB-1895
Fix cve issue and master build
```
[ ] Yes
[X ] No
```

DTSPB-1895 Fix CVE vulnerability and Master build

---

build.gradle

upgrade bintray to jitpack
upgrade bintray to jitpack
```
[ ] Yes
[x] No
```

upgrade bintray to jitpack

---

build.gradle
suppressions.xml

https://tools.hmcts.net/jira/browse/DTSPB-1902
upgrde dependencies
```
[ ] Yes
[ ] No
```

upgrade dependencies

---

audit.json
security.sh

DTSPB-1899
fix nightly master build
```
[ ] Yes
[X ] No
```

Fix for security scan failure

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSPB-1526
bump probate-commons
```
[ ] Yes
[x] No
```

DTSPB-1526: bump probate-commons

---

build.gradle

prod issue debugging
Revert lev commons tag 
```
[ ] Yes
[ X] No
```

Revert lev commons version tag

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/DTSPB-2020
code changes to sync all branches to master with every deployment 
```
[ ] Yes
[ X ] No
```

DTSPB-2020 Sync branches with master code

---

build.gradle
suppressions.xml

https://tools.hmcts.net/jira/browse/DTSPB-2095
Fix CVE-2021-22118
[ ] Yes
[ X ] No

Dtspb 2095 fix CVE 2021 22118

---

security.sh

DTSPB-2168
fix security scan issue
```
[ ] Yes
[X ] No
```

Fix Nightly pipeline

---

Jenkinsfile_CNP
build.gradle
suppressions.xml

https://tools.hmcts.net/jira/browse/DTSPB-2176
Fix the green dependabots in one go
```
[ ] Yes
[X ] No
```

Fix open dependabot PRs

---

build.gradle
src/main/java/uk/gov/hmcts/probate/services/businessdocuments/services/FileSystemResourceService.java

https://tools.hmcts.net/jira/browse/DTSPB-2176
update commonsIO version
```
[ ] Yes
[X ] No
```

update commonsIO version

---

build.gradle
suppressions.xml

https://tools.hmcts.net/jira/browse/DTSPB-2176
dependency upgrades
[ ] Yes
[ X ] No

Dtspb 2175 dependency upgrades

---

suppressions.xml

Suppress failing CVE

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSPB-2176
Fix open dependabot prs
```
[ ] Yes
[X ] No
```

DTSPB-2176 fix open dependabot prs

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSPB-2221
Update tomcat version and fix nightly
```
[ ] Yes
[X ] No
```

DTSPB-2221 Update tomcat version and fix nightly

---

charts/probate-business-service/Chart.yaml
src/main/java/uk/gov/hmcts/probate/services/businessdocuments/services/FileSystemResourceService.java

fix for fortify low vulnerability
[ ] Yes
[ X ] No

Dtspb 2066 fortify fixes

---

Jenkinsfile_nightly
build.gradle
config/fortify-client.properties

DTSPB-2209
integrate fortify in jenkins pipeline
```
[ ] Yes
[X ] No
```

Integrate Fortify with Jenkins

---

suppressions.xml

N/A
Suppress CVE until spring boot upgrade
[ ] Yes
[x] No

suppress CVE until spring boot upgrade

---

charts/probate-business-service/Chart.yaml

https://tools.hmcts.net/jira/browse/DTSPB-2276
- Bump chart.yaml java version to 3.6.0
```
[ ] Yes
[x] No
```

DTSPB-2276 - Bump chart.yaml java version to 3.6.0

---

build.gradle

New commons tag for TC

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSPB-2450
cve fix
```
[ ] Yes
[x] No
```

DTSPB-2450 fix spring core cve

---

build.gradle

Commons changes for will and codicils condition
```
[ ] Yes
[ ] No
```

Commons changes for will and codicils condition

---

build.gradle

Dtspb 2454 ee first page

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSPB-2482
Legal statement change for excepted estate
```
[ ] Yes
[x] No
```

DTSPB-2482: Legal statement change for excepted estate

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSPB-2493
Make ihtFormCompletedOnline optional
```
[ ] Yes
[x] No
```

DTSPB-2493: Make ihtFormCompletedOnline optional

---

charts/probate-business-service/Chart.yaml

https://tools.hmcts.net/jira/browse/DTSPB-2584
```
[ ] Yes
[ x] No
```

DTSPB-2584: Resolve the below deprecated warning form Java repos

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSPB-2586
Fix CVE failure
[ ] Yes
[ X] No

DTSPB-2586 Fix Vulnerabilities

---

build.gradle

DTSPB-2604
```
[ ] Yes
[X ] No
```

DTSPB-2604 Remove the not needed transitive dependency

---

charts/probate-business-service/Chart.yaml

https://tools.hmcts.net/jira/browse/DTSPB-2642
[ ] Yes
[ X ] No

DTSPB-2642 Java chart version upgrade

---

Jenkinsfile_CNP
build.gradle

https://tools.hmcts.net/jira/browse/DTSPB-2616
```
[ ] Yes
[x] No
```

DSTPB-2626 Fix Generating Serenity Report

---

security.sh

https://tools.hmcts.net/jira/browse/DTSPB-2645
```
[ ] Yes
[x] No
```

DTSPB-2645 update security.sh for Nightly Security scan

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSPB-699
Bump probate-commons
```
[ ] Yes
[x] No
```

DTSPB-699: bump probate commons

---

build.gradle
src/test/java/uk/gov/hmcts/probate/services/businessdocuments/controllers/BusinessDocumentControllerTest.java
src/test/java/uk/gov/hmcts/probate/services/businessdocuments/services/FileSystemResourceSystemTest.java
suppressions.xml

https://tools.hmcts.net/jira/browse/DTSPB-2614
epic https://tools.hmcts.net/jira/browse/DTSPB-2611
Spring boot upgrade
[ ] Yes
[X ] No

Dtspb 2614 springboot upgrade

---

build.gradle

DTSPB-2704: Upgrade Springboot version 2.6.6 for probate services

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSPB-2747
[ ] Yes
[X ] No

DTSPB-2747 Fix CVE-2022-22968

---

build.gradle

Dtspb 2544 pp notorial access

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSPB-247
commons change 
```
[ ] Yes
[x] No
```

DTSPB-247 resend email to exec

---

build.gradle

DTSPB-2781: commons upgrade

---

charts/probate-business-service/Chart.yaml
charts/probate-business-service/values.yaml

https://tools.hmcts.net/jira/browse/DTSSE-1517

Autoscaling Update Chart.yaml

---

build.gradle
suppressions.xml

DTSPB-2705 dod equals dob

---

build.gradle
suppressions.xml

DTSPB-2081: solve cve

---

build.gradle

DTSPB-2672: implementing Open ID Connect (OICD)

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSPB-2839
upgrade notify client
```
[ ] Yes
[x] No
```

DTSPB-2839 upgrade notify client

---

build.gradle
src/functionalTest/java/uk/gov/hmcts/probate/functional/BulkScanCoverSheetPDFTest.java
src/functionalTest/resources/json/bulkScanCoverSheet.json
src/main/resources/templates/pdf/bulkScanCoverSheet.html
src/test/java/uk/gov/hmcts/probate/services/businessdocuments/model/BulkScanCoverSheetTest.java
src/test/resources/businessdocuments/validBulkScanCoverSheet.json
src/test/resources/businessdocuments/validBulkScanCoverSheetNoCheckListItems.json
src/test/resources/businessdocuments/validBulkScanCoverSheetStaticTextOverride.json

https://tools.hmcts.net/jira/browse/DTSPB-2725
add new condition in coverheet
```
[ ] Yes
[x] No
```

DTSPB-2725 new condition for no docs required message on PA coversheet

---

charts/probate-business-service/Chart.yaml
suppressions.xml

DTSPB-2892
suppression
```
[ ] Yes
[x] No
```

DTSPB-2892

---

suppressions.xml

DTSPB-2896
```
[ ] Yes
[x] No
```

DTSPB-2896 suppress log4j cve

---

charts/probate-business-service/Chart.yaml

https://tools.hmcts.net/jira/browse/DTSPB-2943
update chart version
```
[ ] Yes
[ ] No
```

DTSPB-2943 - update the version

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSPB-2858
point to commons tag
[ ] Yes
[x] No

DTSPB-2858 point to new comons

---

suppressions.xml

https://tools.hmcts.net/jira/browse/DTSPB-3033
```
[ ] Yes
[ ] No
```

DTSPB-3033 suppress CVE-2022-38752

---

suppressions.xml

https://tools.hmcts.net/jira/browse/DTSPB-3039
```
[ ] Yes
[X] No
```

DTSPB-3039 suppress CVE-2022-42003,CVE-2022-42004

---

build.gradle
suppressions.xml

DTSPB-2997 hand off flag point to new commons

---

build.gradle
suppressions.xml

https://tools.hmcts.net/jira/browse/DTSPB-2407
https://tools.hmcts.net/jira/browse/DTSPB-2656
update probate-commons
```
[ ] Yes
[ ] No
```

DTSPB-2407-PA8A-and-DTSPB-2656-PA8B: update probate commons

---

suppressions.xml

https://tools.hmcts.net/jira/browse/DTSPB-3120
```
[ ] Yes
[X] No
```

DTSPB-3120 Suppress CVE-2022-42252

---

Jenkinsfile_CNP
suppressions.xml

https://tools.hmcts.net/jira/browse/DTSSE-2550

Update Java Chart Jenkinsfile & supps

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSPB-3239
```
[ ] Yes
[X] No
```

DTSPB-3239 Updated commons jar

---

build.gradle
suppressions.xml

DTSPB-3271
```
[ ] Yes
[x] No
```

DTSPB-3271 try update tomcat

---

.dependabot/config.yml
renovate.json

https://tools.hmcts.net/jira/browse/DTSPB-3290
Deleted .dependabot directory and added / updated renovate.json file to match probate-back-office setup.
```
[ ] Yes
[x] No
```

Replacing Dependabot with Renovate

---

charts/probate-business-service/Chart.yaml

https://tools.hmcts.net/jira/browse/DTSSE-2784

Update to Java Chart

---

Jenkinsfile_nightly
build.gradle
suppressions.xml

DTSPB-3321
```
[ ] Yes
[x] No
```

DTSPB-3321 fix build

---

charts/probate-business-service/Chart.yaml

DTSPB-3341
```
[ ] Yes
[x] No
```

DTSPB-3341 update chart

---

suppressions.xml

https://tools.hmcts.net/jira/browse/DTSPB-3390
```
[ ] Yes
[ ] No
```

DTSPB-3390: suppressed new cves

---

suppressions.xml

n/a
dependency suppression
```
[ ] Yes
[x] No
```

add dependency suppression

---

build.gradle

n/a
revert pdf-service-client back to v7.0.0
```
[ ] Yes
[ x] No
```

Fix duplicate jar - nightly build red 

---

build.gradle

Renovate collection

---

suppressions.xml

https://tools.hmcts.net/jira/browse/DTSPB-3494
```
[ ] Yes
[x] No
```

DTSPB-3494 Suppress CVE 2022-1471

---

charts/probate-business-service/Chart.yaml
charts/probate-business-service/values.preview.template.yaml
suppressions.xml

DTSPB-3422: added preview imgress url

---

Dockerfile

DTSPB-3523
revert AI version
```
[ ] Yes
[x] No
```

DTSPB-3523 revert AI version

---

suppressions.xml

https://tools.hmcts.net/jira/browse/DTSPB-3545
```
[ ] Yes
[x] No
```

DTSPB-3405 Sync Probate-commons version

---

build.gradle

DTSPB-3617
address CVE-2023-20883
```
[ ] Yes
[ x] No
```

DTSPB-3617 address CVE-2023-20883

---

renovate.json

https://tools.hmcts.net/jira/browse/DTSPB-3760
```
[ ] Yes
[ x] No
```

DTSPB-3760 update renovate config

---

build.gradle
suppressions.xml

https://tools.hmcts.net/jira/browse/DTSPB-3841 
DTSPB-3841-Fix-CVE-business-service added cve for suppression
```
[ ] Yes
[x] No
```

DTSPB-3841-Fix-CVE-business-service

---

build.gradle
suppressions.xml

https://tools.hmcts.net/jira/browse/DTSPB-3852
https://tools.hmcts.net/jira/browse/DTSPB-3855
```
[ ] Yes
[x ] No
```

DTSPB: 3852 update java logging and  add suppress changes 

---

lib/applicationinsights.json

https://tools.hmcts.net/jira/browse/DTSPB-3625
```
[ ] Yes
[ x] No
```

DTSPB: 3628 update the healthchecks to sampling only 

---

suppressions.xml

DTSPB-3819 surpress CVE

---

suppressions.xml

https://tools.hmcts.net/jira/browse/DTSPB-3930

DTSPB-3930 update suppressions

---

build.gradle

DTSPB-3929 Remove OWASP Dependency Check

---

Jenkinsfile_CNP
Jenkinsfile_parameterized
charts/probate-business-service/values.preview.template.yaml
src/contractTest/resources/application.yml
src/functionalTest/resources/json/inviteDataValid.json
src/main/resources/application.yml
src/test/java/uk/gov/hmcts/probate/services/pin/integration/PinControllerTest.java
src/test/resources/application.yml

https://tools.hmcts.net/jira/browse/DTSPB-3645
```
[ ] Yes
[ x] No
```

DTSPB-3645 added the API key from hardcoded value .

---

Jenkinsfile_nightly

https://tools.hmcts.net/jira/browse/DTSPB-3967

DTSPB-3967 add fortify scan

---

charts/probate-business-service/Chart.yaml

https://tools.hmcts.net/jira/browse/DTSPB-4118

DTSPB-4118  update the chart version enabling hpa 

---

src/functionalTest/java/uk/gov/hmcts/probate/functional/IdamTokenGenerator.java

[DTSPB-3621](https://tools.hmcts.net/jira/browse/DTSPB-3621)
```
[ ] Yes
[x] No
```

DTSPB-3621 Change Open Id token

---

suppressions.xml

https://tools.hmcts.net/jira/browse/DTSPB-4140

DTSPB-4140  add supressions

---

build.gradle

DTSPB-4270
Update commons version
```
[ ] Yes
[X] No
```

DTSPB-4270 Update commons version

---

build.gradle

DTSPB-4293
```
[ ] Yes
[X] No
```

DTSPB-4293 Commons version

---

build.gradle

DTSPB-4582
```
[ ] Yes
[X] No
```

DTSPB-4582 Commons version

---

charts/probate-business-service/Chart.yaml

resolves: DTSPB-4586 https://tools.hmcts.net/jira/browse/DTSPB-4586

DTSPB-4586 update java helm version with oci url

---

src/main/java/uk/gov/hmcts/probate/services/pin/controllers/PinController.java
src/test/java/uk/gov/hmcts/probate/services/pin/integration/PinControllerTest.java

DTSPB-4672
sanitise mobile number before sending pin
```
[ ] Yes
[x] No
```

DTSPB-4672 sanitise mobile number before sending pin

---

build.gradle

DTSPB-4712: Bump SB patch version, resolving CVE

---

build.gradle
config/owasp/suppressions.xml

See [DTSPB-4761](https://tools.hmcts.net/jira/browse/DTSPB-4761)
Converts to using azure artifacts rather than jitpack
```
[ ] Yes
[x] No
```

DTSPB-4761 Convert to using azure artifacts.

---

build.gradle

DTSPB-4368: Remove swagger config

---

build.gradle

DTSPB-4936: Add explicit Tomcat to fix CVE

---

build.gradle

DTSPB-4661
bump commons
```
[ ] Yes
[x] No
```

DTSPB-4661 bump commons
